//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMG.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("char_icon/")]
        public string FormationCharaImagePath {
            get {
                return ((string)(this["FormationCharaImagePath"]));
            }
            set {
                this["FormationCharaImagePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tokeneko_icon/")]
        public string FormationTokeNekoImagePath {
            get {
                return ((string)(this["FormationTokeNekoImagePath"]));
            }
            set {
                this["FormationTokeNekoImagePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".jpg")]
        public string FormationImageExtension {
            get {
                return ((string)(this["FormationImageExtension"]));
            }
            set {
                this["FormationImageExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("未指定")]
        public string FormationImageNothing {
            get {
                return ((string)(this["FormationImageNothing"]));
            }
            set {
                this["FormationImageNothing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("player.csv")]
        public string PLAYER_FILE_NAME {
            get {
                return ((string)(this["PLAYER_FILE_NAME"]));
            }
            set {
                this["PLAYER_FILE_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("formation.csv")]
        public string FORMATION_FILE_NAME {
            get {
                return ((string)(this["FORMATION_FILE_NAME"]));
            }
            set {
                this["FORMATION_FILE_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("character.csv")]
        public string CHARACTER_FILE_NAME {
            get {
                return ((string)(this["CHARACTER_FILE_NAME"]));
            }
            set {
                this["CHARACTER_FILE_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("guild.csv")]
        public string GUILD_FILE_NAME {
            get {
                return ((string)(this["GUILD_FILE_NAME"]));
            }
            set {
                this["GUILD_FILE_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("playerVSplayer.csv")]
        public string PLAYERVSPLAYER_FILE_NAME {
            get {
                return ((string)(this["PLAYERVSPLAYER_FILE_NAME"]));
            }
            set {
                this["PLAYERVSPLAYER_FILE_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("formationVSFormation.csv")]
        public string FORMATIONVSFORMATION_FILE_NAME {
            get {
                return ((string)(this["FORMATIONVSFORMATION_FILE_NAME"]));
            }
            set {
                this["FORMATIONVSFORMATION_FILE_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SERVER_TIME_CORRECTION_SECONDS {
            get {
                return ((int)(this["SERVER_TIME_CORRECTION_SECONDS"]));
            }
            set {
                this["SERVER_TIME_CORRECTION_SECONDS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.8")]
        public float DEFENSE_TIME {
            get {
                return ((float)(this["DEFENSE_TIME"]));
            }
            set {
                this["DEFENSE_TIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("全ギルド選択")]
        public string SELECT_GUILD_ALL_STR {
            get {
                return ((string)(this["SELECT_GUILD_ALL_STR"]));
            }
            set {
                this["SELECT_GUILD_ALL_STR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("data/")]
        public string BASE_DATA_PATH {
            get {
                return ((string)(this["BASE_DATA_PATH"]));
            }
            set {
                this["BASE_DATA_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ulong DISCORD_SERVER_ADMIN_CLIENT_ID {
            get {
                return ((ulong)(this["DISCORD_SERVER_ADMIN_CLIENT_ID"]));
            }
            set {
                this["DISCORD_SERVER_ADMIN_CLIENT_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ulong DISCORD_BOT_CLIENT_ID {
            get {
                return ((ulong)(this["DISCORD_BOT_CLIENT_ID"]));
            }
            set {
                this["DISCORD_BOT_CLIENT_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ulong DISCORD_WEEK_PASS_CHANNEL_ID {
            get {
                return ((ulong)(this["DISCORD_WEEK_PASS_CHANNEL_ID"]));
            }
            set {
                this["DISCORD_WEEK_PASS_CHANNEL_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ulong DISCORD_MMGP_CHANNEL_ID {
            get {
                return ((ulong)(this["DISCORD_MMGP_CHANNEL_ID"]));
            }
            set {
                this["DISCORD_MMGP_CHANNEL_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DISCORD_WEEK_PASS_CHANNEL_CLIENT_IDS {
            get {
                return ((string)(this["DISCORD_WEEK_PASS_CHANNEL_CLIENT_IDS"]));
            }
            set {
                this["DISCORD_WEEK_PASS_CHANNEL_CLIENT_IDS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BOT_TOKEN {
            get {
                return ((string)(this["BOT_TOKEN"]));
            }
            set {
                this["BOT_TOKEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("discord.csv")]
        public string DISCORD_FILE_NAME {
            get {
                return ((string)(this["DISCORD_FILE_NAME"]));
            }
            set {
                this["DISCORD_FILE_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("guild_img/")]
        public string GuildImagePath {
            get {
                return ((string)(this["GuildImagePath"]));
            }
            set {
                this["GuildImagePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bak/")]
        public string BACKUP_DIR {
            get {
                return ((string)(this["BACKUP_DIR"]));
            }
            set {
                this["BACKUP_DIR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MementoMori")]
        public string PROCESS_TITLE_NAME {
            get {
                return ((string)(this["PROCESS_TITLE_NAME"]));
            }
            set {
                this["PROCESS_TITLE_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mTemp/")]
        public string MATCH_TEMP_DIR {
            get {
                return ((string)(this["MATCH_TEMP_DIR"]));
            }
            set {
                this["MATCH_TEMP_DIR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("char_pm/")]
        public string MATCH_CHARACTER_DIR {
            get {
                return ((string)(this["MATCH_CHARACTER_DIR"]));
            }
            set {
                this["MATCH_CHARACTER_DIR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.8")]
        public double MATCH_THRESHOLD {
            get {
                return ((double)(this["MATCH_THRESHOLD"]));
            }
            set {
                this["MATCH_THRESHOLD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("char_pm_gvs/")]
        public string MATCH_GUILDVS_CHARACTER_DIR {
            get {
                return ((string)(this["MATCH_GUILDVS_CHARACTER_DIR"]));
            }
            set {
                this["MATCH_GUILDVS_CHARACTER_DIR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("player_pm_gvs/")]
        public string MATCH_GUILDVS_PLAYER_DIR {
            get {
                return ((string)(this["MATCH_GUILDVS_PLAYER_DIR"]));
            }
            set {
                this["MATCH_GUILDVS_PLAYER_DIR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MATCH_TEMP_DIR_MAX_SIZE {
            get {
                return ((int)(this["MATCH_TEMP_DIR_MAX_SIZE"]));
            }
            set {
                this["MATCH_TEMP_DIR_MAX_SIZE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3,5,1,0.8,0.4")]
        public string MATCH_AUTO_INTERVAL_TIMES {
            get {
                return ((string)(this["MATCH_AUTO_INTERVAL_TIMES"]));
            }
            set {
                this["MATCH_AUTO_INTERVAL_TIMES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("div/")]
        public string MATCH_TEMP_DIV_DIR {
            get {
                return ((string)(this["MATCH_TEMP_DIV_DIR"]));
            }
            set {
                this["MATCH_TEMP_DIV_DIR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("メメントモリサブ垢003,メメントモリサブ垢002兼用")]
        public string MATCH_WINDOW_TITLE_NAMES {
            get {
                return ((string)(this["MATCH_WINDOW_TITLE_NAMES"]));
            }
            set {
                this["MATCH_WINDOW_TITLE_NAMES"] = value;
            }
        }
    }
}
